#use_frameworks!

platform :ios, '8.0'

target 'PoporFFmpegCompress_Example' do
  pod 'PoporFFmpegCompress', :path => '../'

  target 'PoporFFmpegCompress_Tests' do
    inherit! :search_paths

    
  end
end
